### PR TITLE
use url instead of permalink

### PR DESCRIPTION
**Pull request by deargle**

### CODE REVIEW

**Comment by deargle** [comment]
See #42. I'm now looking into why the .active style is missing.

**Comment by deargle** [comment]
Closes #42

**Review by benbalter — APPROVED** [review]
Per [the docs](https://getbootstrap.com/docs/4.0/components/navbar/#nav):

> Active states—with .active—to indicate the current page can be applied directly to .nav-links or their immediate parent .nav-items.

So I'm not sure why moving it affected the output, but if it works for your use case and doesn't break others, 👍🏻 . Thanks for the PR.

**Comment by deargle** [comment]
Yeah there's definitely a discrepancy between the bootstrap docs and what their css actually currently does. Community-mindedness would say that my next move is to open a PR for bootstrap -- or at least an issue -- but my lower back says I need to spend less time on my computer.

**Pull request merged**
